package dev.iyanz.sessentials;

import java.util.List;

import dev.iyanz.sessentials.api.EssModule;

/**
 * The registry of feature modules to enable, in order. This is the single place that
 * lists modules; each module is otherwise self-contained.
 */
final class Modules {

    private Modules() {
    }

    static List<EssModule> all() {
        return List.of(
                new dev.iyanz.sessentials.module.teleport.TeleportModule(),
                new dev.iyanz.sessentials.module.home.HomeModule(),
                new dev.iyanz.sessentials.module.warp.WarpModule(),
                new dev.iyanz.sessentials.module.playerstate.PlayerStateModule(),
                new dev.iyanz.sessentials.module.items.ItemsModule(),
                new dev.iyanz.sessentials.module.worldtime.WorldTimeModule(),
                new dev.iyanz.sessentials.module.messaging.MessagingModule(),
                new dev.iyanz.sessentials.module.moderation.ModerationModule(),
                new dev.iyanz.sessentials.module.economy.EconomyModule(),
                new dev.iyanz.sessentials.module.kits.KitsModule(),
                new dev.iyanz.sessentials.module.identity.IdentityModule(),
                new dev.iyanz.sessentials.module.utility.UtilityModule(),
                new dev.iyanz.sessentials.module.admin.AdminModule(),
                new dev.iyanz.sessentials.module.jail.JailModule(),
                new dev.iyanz.sessentials.module.mail.MailModule(),
                new dev.iyanz.sessentials.module.ignore.IgnoreModule(),
                new dev.iyanz.sessentials.module.playtime.PlaytimeModule(),
                new dev.iyanz.sessentials.module.info.InfoModule(),
                new dev.iyanz.sessentials.module.worlds.WorldsModule(),
                new dev.iyanz.sessentials.module.chat.ChatModule(),
                new dev.iyanz.sessentials.module.inspect.InspectModule(),
                new dev.iyanz.sessentials.module.fun.FunModule(),
                new dev.iyanz.sessentials.module.warnings.WarningsModule(),
                new dev.iyanz.sessentials.module.combat.CombatModule(),
                new dev.iyanz.sessentials.module.econextra.EconExtraModule(),
                new dev.iyanz.sessentials.module.utility2.Utility2Module(),
                new dev.iyanz.sessentials.module.scavenger.ScavengerModule(),
                new dev.iyanz.sessentials.module.exp.ExpModule(),
                new dev.iyanz.sessentials.module.deathmessages.DeathMessagesModule(),
                new dev.iyanz.sessentials.module.autobroadcast.AutoBroadcastModule(),
                new dev.iyanz.sessentials.module.customalias.CustomAliasModule(),
                new dev.iyanz.sessentials.module.cmdcontrol.CmdControlModule(),
                new dev.iyanz.sessentials.module.holograms.HologramsModule(),
                new dev.iyanz.sessentials.module.portals.PortalsModule(),
                new dev.iyanz.sessentials.module.signs.SignsModule(),
                new dev.iyanz.sessentials.module.recipes.RecipesModule(),
                new dev.iyanz.sessentials.module.playtimerewards.PlaytimeRewardsModule(),
                new dev.iyanz.sessentials.module.placeholders.PlaceholdersModule(),
                new dev.iyanz.sessentials.module.chatformat.ChatFormatModule(),
                new dev.iyanz.sessentials.module.chatfilter.ChatFilterModule(),
                new dev.iyanz.sessentials.module.playeroptions.PlayerOptionsModule(),
                new dev.iyanz.sessentials.module.notify.NotifyModule(),
                new dev.iyanz.sessentials.module.worldtools.WorldToolsModule(),
                new dev.iyanz.sessentials.module.invtools.InvToolsModule(),
                new dev.iyanz.sessentials.module.hpbar.HpBarModule(),
                new dev.iyanz.sessentials.module.painting.PaintingModule(),
                new dev.iyanz.sessentials.module.armorstand.ArmorStandModule(),
                new dev.iyanz.sessentials.module.disableenchant.DisableEnchantModule(),
                new dev.iyanz.sessentials.module.colorlimits.ColorLimitsModule(),
                new dev.iyanz.sessentials.module.timedcommands.TimedCommandsModule(),
                new dev.iyanz.sessentials.module.savedinv.SavedInvModule(),
                new dev.iyanz.sessentials.module.nbt.NbtModule(),
                new dev.iyanz.sessentials.module.stats.StatsModule(),
                new dev.iyanz.sessentials.module.attachedcommands.AttachedCommandsModule(),
                new dev.iyanz.sessentials.module.ctellraw.CTellrawModule(),
                new dev.iyanz.sessentials.module.armoreffects.ArmorEffectsModule(),
                new dev.iyanz.sessentials.module.elytra.ElytraModule(),
                new dev.iyanz.sessentials.module.ipinfo.IpInfoModule(),
                new dev.iyanz.sessentials.module.anvilcost.AnvilCostModule(),
                new dev.iyanz.sessentials.module.cmdwarmup.CmdWarmupModule(),
                new dev.iyanz.sessentials.module.falldistance.FallDistanceModule(),
                new dev.iyanz.sessentials.module.counter.CounterModule(),
                new dev.iyanz.sessentials.module.silentchest.SilentChestModule(),
                new dev.iyanz.sessentials.module.ctext.CTextModule(),
                new dev.iyanz.sessentials.module.commandspy.CommandSpyModule(),
                new dev.iyanz.sessentials.module.afkkick.AfkKickModule(),
                new dev.iyanz.sessentials.module.firstjoin.FirstJoinModule(),
                new dev.iyanz.sessentials.module.emoji.EmojiModule(),
                new dev.iyanz.sessentials.module.antispam.AntiSpamModule(),
                new dev.iyanz.sessentials.module.backpack.BackpackModule(),
                new dev.iyanz.sessentials.module.glow.GlowModule(),
                new dev.iyanz.sessentials.module.spawner.SpawnerModule(),
                new dev.iyanz.sessentials.module.vopen.VOpenModule(),
                new dev.iyanz.sessentials.module.staffchat.StaffChatModule(),
                new dev.iyanz.sessentials.module.helpop.HelpOpModule(),
                new dev.iyanz.sessentials.module.note.NoteModule(),
                new dev.iyanz.sessentials.module.report.ReportModule(),
                new dev.iyanz.sessentials.module.trade.TradeModule(),
                new dev.iyanz.sessentials.module.joinmessages.JoinMessagesModule(),
                new dev.iyanz.sessentials.module.localchat.LocalChatModule(),
                new dev.iyanz.sessentials.module.butcher.ButcherModule(),
                new dev.iyanz.sessentials.module.entities.EntitiesModule(),
                new dev.iyanz.sessentials.module.clearground.ClearGroundModule(),
                new dev.iyanz.sessentials.module.coinflip.CoinFlipModule(),
                new dev.iyanz.sessentials.module.lottery.LotteryModule(),
                new dev.iyanz.sessentials.module.chestlock.ChestLockModule(),
                new dev.iyanz.sessentials.module.itemframe.ItemFrameModule(),
                new dev.iyanz.sessentials.module.grave.GraveModule(),
                new dev.iyanz.sessentials.module.mutechat.MuteChatModule(),
                new dev.iyanz.sessentials.module.slowmode.SlowModeModule(),
                new dev.iyanz.sessentials.module.ipban.IpBanModule(),
                new dev.iyanz.sessentials.module.tempfly.TempFlyModule(),
                new dev.iyanz.sessentials.module.nightvision.NightVisionModule(),
                new dev.iyanz.sessentials.module.adminbatch.AdminBatchModule(),
                new dev.iyanz.sessentials.module.title.TitleModule(),
                new dev.iyanz.sessentials.module.broadcastsound.BroadcastSoundModule(),
                new dev.iyanz.sessentials.module.kittycannon.KittyCannonModule(),
                new dev.iyanz.sessentials.module.expbottle.ExpBottleModule(),
                new dev.iyanz.sessentials.module.vitals.VitalsModule(),
                new dev.iyanz.sessentials.module.lockdown.LockdownModule(),
                new dev.iyanz.sessentials.module.menus.MenusModule(),
                new dev.iyanz.sessentials.module.damageindicator.DamageIndicatorModule(),
                new dev.iyanz.sessentials.module.repairall.RepairAllModule(),
                new dev.iyanz.sessentials.module.burn.BurnModule(),
                new dev.iyanz.sessentials.module.fireball.FireballModule(),
                new dev.iyanz.sessentials.module.craft.CraftModule(),
                new dev.iyanz.sessentials.module.sendspawn.SendSpawnModule(),
                new dev.iyanz.sessentials.module.healall.HealAllModule(),
                new dev.iyanz.sessentials.module.feedall.FeedAllModule(),
                new dev.iyanz.sessentials.module.smite.SmiteModule(),
                new dev.iyanz.sessentials.module.sit.SitModule(),
                new dev.iyanz.sessentials.module.itemadmin.ItemAdminModule(),
                new dev.iyanz.sessentials.module.attributes.AttributesModule(),
                new dev.iyanz.sessentials.module.staffextras.StaffExtrasModule(),
                new dev.iyanz.sessentials.module.serverextras.ServerExtrasModule(),
                new dev.iyanz.sessentials.module.economyprovider.EconomyProviderModule(),
                new dev.iyanz.sessentials.module.cmiextras.CmiExtrasModule(),
                new dev.iyanz.sessentials.module.buildtools.BuildToolsModule(),
                new dev.iyanz.sessentials.module.managegui.ManageGuiModule(),
                new dev.iyanz.sessentials.module.guiextras.GuiExtrasModule(),
                new dev.iyanz.sessentials.module.warpadmin.WarpAdminModule(),
                new dev.iyanz.sessentials.module.tpmenu.TpMenuModule(),
                new dev.iyanz.sessentials.module.playerlist.PlayerListModule(),
                new dev.iyanz.sessentials.module.kiteditor.KitEditorModule(),
                new dev.iyanz.sessentials.module.nicheextras.NicheExtrasModule(),
                new dev.iyanz.sessentials.module.bedhome.BedHomeModule(),
                new dev.iyanz.sessentials.module.hub.HubModule(),
                new dev.iyanz.sessentials.module.itembrowser.ItemBrowserModule(),
                new dev.iyanz.sessentials.module.adminguis.AdminGuisModule(),
                new dev.iyanz.sessentials.module.itemcmds.ItemCmdsModule(),
                new dev.iyanz.sessentials.module.protection.ProtectionModule(),
                new dev.iyanz.sessentials.module.joinbehavior.JoinBehaviorModule(),
                new dev.iyanz.sessentials.module.worldbehavior.WorldBehaviorModule(),
                new dev.iyanz.sessentials.module.elevatorsigns.ElevatorSignsModule()
        );
    }
}
